# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0339bcc8bd9735a579dfe06ffed6effed02bde23b8466fecbdf0f341e453c662d6694b6e9b96effa16a95c18327c5a35bcb5a071398e879c2fe685461c2049e6

test:
  secret_key_base: 0f6293ce09228f282038a36d5c501698439af2f83ce2d2ca6fd3ba05ea71898a67e3bdfdeb4f4135b4fe0545800707d62c1e0109e439e8c7e68c82515b73c0b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
